### ISSUE TITLE
gpt-4o-canvas의 모델명 표시

### ISSUE THREAD

**Issue by jongwoo328** [cheolm1n/promptly#11]
gpt-4o-canvas의 경우
표시는 gpt-4o-canvas로 표시되고 있지만 파라미터에 표시되는 모델정보는 gpt-4o-canmore 인데요
저도 이 버튼의 모델이 뭐지 해서 찾아보고 알아낸거라

메인페이지의 버튼에는 사용자에게 친숙한 형태인 gpt-4o-canvas로 표시되고 파라미터로 gpt-4o-canmore가 전달되면 더 좋을 것 같아서 제안합니다

**Comment by cheolm1n** [comment]
#12 에서 퍼플렉시티 추가와 함께 반영했습니다.
