### ISSUE TITLE
Main에서 드롭다운 메뉴 위로 마우스가 이동할 경우 화면 내 요소들이 왼쪽으로 이동하는 문제

### ISSUE THREAD

**Issue by cheolm1n** [cheolm1n/promptly#13]
# 현상
Main에서 드롭다운 메뉴 위로 마우스가 이동할 경우 화면 내 요소들이 왼쪽으로 이동하는 문제가 있습니다.

# 재현

https://github.com/user-attachments/assets/9be8d39b-0c89-4540-b00f-dc61ba9baa92

**Comment by jongwoo328** [comment]
저는 재현이 안되네요

**Comment by cheolm1n** [comment]
> 저는 재현이 안되네요

스크린샷말고 영상으로 올렸는데, 재현이 안되시나요?

**Comment by jongwoo328** [comment]
아 확인했어요 프롬프트가 길어서한번에 표현이 안되는경우에 발생하네요

**Comment by cheolm1n** [comment]
#14 에서 해결하였습니다.
