### ISSUE TITLE
sync 사이즈 제한

### ISSUE THREAD

**Issue by jongwoo328** [cheolm1n/promptly#18]
sync 저장소에 각 항목당 크기 제한과 전체 크기 제한이 있으며
이는 sync 저장소에 set을 호출하면 `chrome.runtime.lastError`에 정보가 저장됩니다.

그런데 문서에 따르면 lastError에는 human readable 메시지가 저장되고
해당 메시지는 영어만 제공되는데 이건 어떡하면 좋을까요? 

set 콜백에서
`console.log('lasterror', chrome.runtime.lastError)` 실행결과
<img width="626" alt="image" src="https://github.com/user-attachments/assets/7141a00e-ffd2-4e98-826c-3ce5eb3df66e">

**Comment by jongwoo328** [comment]
따로 에러 코드도 없고 그냥 전역 변수에 에러가 발생할때마다 메시지만 덮어씌워지는 구조입니다

**Comment by cheolm1n** [comment]
저 에러에 대한 코드는 지정되어 있지 않나요? 
에러 코드를 보고 각 언어에 따라 에러메시지를 주면 좋을 것 같아요.
에러 코드가 없다면 저 메시지 또는 그냥 에러 발생시 메시지를 띄워도 상관 없을 것 같구요

```
저장 용량을 초과하여 저장할 수 없습니다. 전체 프롬프트의 개수 또는 길이를 줄여주세요.

The storage limit has been exceeded. Please reduce the number or length of the prompts.
```
