### ISSUE TITLE
신규 기능 제안

### ISSUE THREAD

**Issue by cheolm1n** [cheolm1n/promptly#23]
다음은 논의를 통해서 채택 여부를 결정 해야 할 신규 기능에 대한 아이디어입니다.
(제 생각 + 주변의 제안)

---

- [x] 웹페이지에서 텍스트 선택 후 우클릭 메뉴로 프롬프트를 추가 할 수 있도록 기능 추가
- [x] 프롬프트 검색을 통한 선택 기능 추가
- [ ] 새 창이 아닌 현재창에서 실행 기능 추가
- [x] 프롬프트 제목 추가
- [ ] 이전 실행 기록 (히스토리)
- [x] 시스템폰트가 아닌 무료 폰트로 변경
- [x] 토스트 위치 변경 (위 -> 아래)

**Comment by jongwoo328** [comment]
저희 개발환경이 맥이다 보니 다른 환경에서 실행하면 개발할 때 보는것과 느낌이 다르게 전달될 수 있어서 디자인을 의도대로 전달하려면 시스템 폰트가 아닌 다른 폰트로 변경하는건 필요할 것 같네요

**Comment by cheolm1n** [comment]
> 저희 개발환경이 맥이다 보니 다른 환경에서 실행하면 개발할 때 보는것과 느낌이 다르게 전달될 수 있어서 디자인을 의도대로 전달하려면 시스템 폰트가 아닌 다른 폰트로 변경하는건 필요할 것 같네요

스샷 다시 만들 생각에 눈물이... 🥲

**Comment by jongwoo328** [comment]
웹페이지에서 텍스트 선택 후 우클릭 메뉴로 프롬프트를 추가 할 수 있도록 기능 추가 해볼게요

**Comment by jongwoo328** [comment]
제목추가 해볼게요

**Comment by cheolm1n** [comment]
> 제목추가 해볼게요

넵 크리스마스인데 쉬엄쉬엄 하세요 🎅🎄

전 그럼 하기로 했던건 아니지만... 폰트 변경 해보겠습니다.

**Comment by cheolm1n** [comment]
진행하기로 했던 수정사항들 모두 반영했으니 해당 이슈는 클로즈 하겠습니다.
