### ISSUE TITLE
코드 포매터 추가

### ISSUE THREAD

**Issue by jongwoo328** [cheolm1n/promptly#31]
@cheolm1n 
이때까지 수작업으로 하고 있었는데 코드 포매팅 양식(`prettierrc`, `eslintrc`)을 프로젝트에 추가해서 맞추는게 어떨까요?
괜찮으면 추가해볼게요

**Comment by cheolm1n** [comment]
> @cheolm1n 
> 이때까지 수작업으로 하고 있었는데 코드 포매팅 양식(`prettierrc`, `eslintrc`)을 프로젝트에 추가해서 맞추는게 어떨까요?
> 괜찮으면 추가해볼게요

좋습니다... 그럴 때가 왔군요

**Comment by jongwoo328** [comment]
pr 다 머지되면 한번에 적용해서 올릴게요

**Comment by cheolm1n** [comment]
> pr 다 머지되면 한번에 적용해서 올릴게요

전부 머지했습니다~
